package com.qiyam.islamic.provider;

import com.qiyam.islamic.dto.HadithReferenceDto;
import com.qiyam.islamic.dto.HadithResponse;
import com.qiyam.islamic.exception.ExternalServiceUnavailableException;
import com.qiyam.shared.config.AppProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

import java.net.URI;

/**
 * Fetches hadith text from the fawazahmed0/hadith-api open dataset, served as static JSON over
 * the jsDelivr CDN — free, no API key, no rate limit of its own. Text (and its translator
 * attribution) is proxied verbatim and never generated by this service.
 */
@Slf4j
@Component
public class HadithProvider {

    private final RestTemplate restTemplate;
    private final String baseUrl;

    public HadithProvider(RestTemplate restTemplate, AppProperties appProperties) {
        this.restTemplate = restTemplate;
        this.baseUrl = appProperties.islamic().hadithApiBaseUrl();
    }

    /** @param collection e.g. "bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah" */
    public HadithResponse getHadith(String collection, int hadithNumber) {
        var edition = "eng-" + collection.toLowerCase();
        var uri = URI.create(baseUrl + "/editions/" + edition + "/" + hadithNumber + ".min.json");

        HadithApiResponse response;
        try {
            response = restTemplate.getForObject(uri, HadithApiResponse.class);
        } catch (HttpClientErrorException.NotFound e) {
            throw new IllegalArgumentException(
                    "No hadith found for collection '" + collection + "' number " + hadithNumber);
        } catch (RestClientException e) {
            log.error("Hadith dataset request failed for {}: {}", uri, e.getMessage());
            throw new ExternalServiceUnavailableException("Hadith service temporarily unavailable", e);
        }

        if (response == null || response.hadiths() == null || response.hadiths().isEmpty()) {
            log.error("Hadith dataset returned an unexpected/empty response for {}", uri);
            throw new ExternalServiceUnavailableException("Hadith service temporarily unavailable");
        }

        var hadith = response.hadiths().get(0);
        var collectionName = response.metadata() != null ? response.metadata().name() : collection;
        var reference = hadith.reference() != null
                ? new HadithReferenceDto(hadith.reference().book(), hadith.reference().hadith())
                : null;

        return new HadithResponse(collection.toLowerCase(), collectionName, edition,
                hadith.hadithnumber(), hadith.text(), reference);
    }
}
