package com.qiyam.islamic.provider;

import com.qiyam.islamic.dto.QuranAyahDto;
import com.qiyam.islamic.dto.QuranSurahResponse;
import com.qiyam.islamic.exception.ExternalServiceUnavailableException;
import com.qiyam.shared.config.AppProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.UriComponentsBuilder;

import java.util.Comparator;
import java.util.List;

/**
 * Fetches Quran text from alquran.cloud (api.alquran.cloud) — free, no API key required, run by
 * the same Islamic Network team behind Aladhan. Always requests the Uthmani Arabic text alongside
 * a translation edition; text is proxied verbatim and never generated by this service.
 */
@Slf4j
@Component
public class QuranProvider {

    private static final String ARABIC_EDITION = "quran-uthmani";

    private final RestTemplate restTemplate;
    private final String baseUrl;

    public QuranProvider(RestTemplate restTemplate, AppProperties appProperties) {
        this.restTemplate = restTemplate;
        this.baseUrl = appProperties.islamic().quranApiBaseUrl();
    }

    /** Fetches an entire surah with every ayah's Arabic text + translation. */
    public QuranSurahResponse getSurah(int surahNumber, String translationEdition) {
        var uri = UriComponentsBuilder
                .fromUriString(baseUrl + "/surah/" + surahNumber + "/editions/" + ARABIC_EDITION + "," + translationEdition)
                .build().toUri();
        var response = fetch(uri);

        var arabic = findEdition(response, ARABIC_EDITION, uri);
        var translation = findEdition(response, translationEdition, uri);

        var arabicByNumber = arabic.ayahs().stream()
                .collect(java.util.stream.Collectors.toMap(AlQuranCloudResponse.Ayah::numberInSurah, a -> a));
        var ayahs = translation.ayahs().stream()
                .sorted(Comparator.comparingInt(AlQuranCloudResponse.Ayah::numberInSurah))
                .map(t -> {
                    var a = arabicByNumber.get(t.numberInSurah());
                    return new QuranAyahDto(t.numberInSurah(), a != null ? a.text() : null, t.text());
                })
                .toList();

        return new QuranSurahResponse(arabic.number(), arabic.name(), arabic.englishName(),
                arabic.englishNameTranslation(), arabic.revelationType(), translationEdition, ayahs);
    }

    /** Fetches a single ayah by surah:ayah reference (e.g. surah 2, ayah 255 → "2:255"). */
    public QuranSurahResponse getAyah(int surahNumber, int ayahNumber, String translationEdition) {
        var uri = UriComponentsBuilder
                .fromUriString(baseUrl + "/ayah/" + surahNumber + ":" + ayahNumber + "/editions/" + ARABIC_EDITION + "," + translationEdition)
                .build().toUri();
        var response = fetch(uri);

        var arabic = findEdition(response, ARABIC_EDITION, uri);
        var translation = findEdition(response, translationEdition, uri);
        if (arabic.surah() == null || translation.numberInSurah() == null) {
            log.error("alquran.cloud returned an unexpected ayah response for {}", uri);
            throw new ExternalServiceUnavailableException("Quran service temporarily unavailable");
        }

        var ayah = new QuranAyahDto(translation.numberInSurah(), arabic.text(), translation.text());
        return new QuranSurahResponse(arabic.surah().number(), arabic.surah().name(), arabic.surah().englishName(),
                arabic.surah().englishNameTranslation(), arabic.surah().revelationType(), translationEdition, List.of(ayah));
    }

    private AlQuranCloudResponse fetch(java.net.URI uri) {
        try {
            var response = restTemplate.getForObject(uri, AlQuranCloudResponse.class);
            if (response == null || response.data() == null || response.data().isEmpty()) {
                throw new ExternalServiceUnavailableException("Quran service temporarily unavailable");
            }
            return response;
        } catch (HttpClientErrorException.NotFound e) {
            throw new IllegalArgumentException("Surah/ayah not found — check the surah (1-114) and ayah numbers");
        } catch (RestClientException e) {
            log.error("alquran.cloud request failed for {}: {}", uri, e.getMessage());
            throw new ExternalServiceUnavailableException("Quran service temporarily unavailable", e);
        }
    }

    private AlQuranCloudResponse.EditionBlock findEdition(AlQuranCloudResponse response, String editionId, java.net.URI uri) {
        return response.data().stream()
                .filter(block -> block.edition() != null && editionId.equals(block.edition().identifier()))
                .findFirst()
                .orElseThrow(() -> {
                    log.error("alquran.cloud response for {} did not include edition {}", uri, editionId);
                    return new ExternalServiceUnavailableException("Quran service temporarily unavailable");
                });
    }
}
